# Generated by Django 4.1.7 on 2023-04-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='vt_key',
            field=models.CharField(default='', max_length=256),
        ),
    ]
