# Generated by Django 4.1.7 on 2023-04-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('keyword', models.CharField(default='', max_length=256)),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(default='', max_length=256)),
                ('city', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
