# Generated by Django 4.1.7 on 2023-04-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulsearch', '0003_records2_delete_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records2',
            new_name='Records',
        ),
    ]
