# Generated by Django 4.1.7 on 2023-04-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dirscan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dirs',
            name='service',
        ),
    ]
