# Generated by Django 4.1.7 on 2023-04-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirscan', '0002_remove_dirs_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirs',
            name='dir',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
