# Generated by Django 4.1.7 on 2023-04-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('domin', models.CharField(max_length=100)),
                ('subdomin', models.CharField(default='/', max_length=100)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
