# Generated by Django 4.1.7 on 2023-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnssearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('subdomain', models.CharField(default='', max_length=100)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Domins',
        ),
    ]
