# Generated by Django 4.1.7 on 2023-04-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnssearch', '0002_domains_delete_domins'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
